[build]
  # Build command - includes copying images and sounds
  command = "cd client && npm install && npm run build && mkdir -p build/uploads && mkdir -p build/sounds && cp -r server/uploads/* build/uploads/ || echo 'No uploads to copy' && cp -r public/sounds/* build/sounds/ || echo 'No sounds to copy'"
  
  # Directory to publish
  publish = "client/build"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirect API image files to Netlify function with proper path preservation
[[redirects]]
  from = "/api/images/*"
  to = "/.netlify/functions/api/images/:splat"
  status = 200
  force = true

# Redirect API sound files to Netlify function with proper path preservation
[[redirects]]
  from = "/api/sounds/*"
  to = "/.netlify/functions/api/sounds/:splat"
  status = 200
  force = true

# Redirect all other API calls to unified function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# Try direct access to sound files first
[[redirects]]
  from = "/sounds/*"
  to = "/sounds/:splat"
  status = 200
  
# Fallback to API function for sound files if direct access fails
[[redirects]]
  from = "/sounds/*"
  to = "/.netlify/functions/api/sounds/:splat"
  status = 200

# SPA fallback - send all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200